/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'outline': '#909097',
        'secondary': '#4edea3',
        'inverse-on-surface': '#283044',
        'on-error': '#690005',
        'inverse-surface': '#dae2fd',
        'on-primary': '#00354a',
        'surface-container-low': '#131b2e',
        'on-secondary': '#003824',
        'surface-variant': '#2d3449',
        'background': '#0b1326',
        'primary-container': '#001a27',
        'surface-container-highest': '#2d3449',
        'tertiary-container': '#251400',
        'error-container': '#93000a',
        'primary': '#7bd0ff',
        'inverse-primary': '#00668a',
        'surface-container-lowest': '#060e20',
        'on-background': '#dae2fd',
        'on-surface-variant': '#c6c6cd',
        'on-surface': '#dae2fd',
        'outline-variant': '#45464d',
        'on-tertiary': '#472a00',
        'surface': '#0b1326',
        'on-error-container': '#ffdad6',
        'surface-bright': '#31394d',
        'surface-container-high': '#222a3d',
        'surface-container': '#171f33',
        'tertiary': '#ffb95f',
        'surface-tint': '#7bd0ff',
        'secondary-container': '#00a572',
        'error': '#ffb4ab',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Space Grotesk', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        '3xl': '1rem',
        '4xl': '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
